### ISSUE TITLE
document the procedure to regenerate `model4cells_train_split_3_50_dims.pkl`

### ISSUE THREAD

**Issue by cameronraysmith** [pinellolab/DNA-Diffusion#106]
In #101 a model file was introduced.
We should document how to regenerate it and remove it from the repository.

**Comment by ttunja** [comment]
@noahweber1 comment here regarding training the vq_vae

**Comment by cameronraysmith** [comment]
https://github.com/pinellolab/DNA-Diffusion/pull/101#issuecomment-1481647733
