### ISSUE TITLE
Create function motif_count Input

### ISSUE THREAD

**Issue by lucapinello** [pinellolab/DNA-Diffusion#13]
def motif_count Input(sequences, return_probability=False)

'sequences': list of sequences to scan
return_probability: if True scale the occurrences based on the total number of sequences in input 
Return: pandas dataframe with  index  'motif_id_name' value: 'occurences'  (or 'probability') of motif in the sequences

**Comment by sg134** [comment]
Can I try working on this?

**Comment by sg134** [comment]
Can I try working on this?
