### ISSUE TITLE
dev version of package not installed by default in slurm job-accessible conda environment

### ISSUE THREAD

**Issue by ssenan** [pinellolab/DNA-Diffusion#134]
* Combining the two codebases broke various pathing requirements for loading data files and scripts

**Comment by cameronraysmith** [comment]
In #133 we forgot to include what is required to install the package in development mode. Roughly speaking, we need to update the scripts and configuration to do the following

1. require install of `conda-build` in the `environment.yml` file or install it manually from a script to keep it clean
2. run the correct `conda-develop -n dnadiffusion .` command from the write location and with the `dnadiffusion` environment activated
3. check the conda.pth file and/or `python -m site` output to see the path to the local development copy of the package has been added by `conda-develop`

**Comment by ssenan** [comment]
I tested this on the cluster and found that it's important to run conda-develop within the src directory to ensure we are able to import dnadiffusion correctly. As discussed earlier I'll leave this to be resolved in your upcoming PR.

**Comment by noahweber1** [comment]
@ssenan @cameronraysmith whats the status on this, can we close it?

**Comment by cameronraysmith** [comment]
@noahweber1 it's not resolved just yet in the sense that we have a solution but have not created a PR that implements it. A solution will likely just need to update the instructions in [`environments/cluster/README.md`](https://github.com/pinellolab/DNA-Diffusion/blob/b4ba5aac9ad1b3ef6efa4dd2994a5542ac9cf123/environments/cluster/README.md).

@ssenan 

```bash
conda develop -n dnadiffusion ./src/
```

, which I know I originally suggested, just adds the full path to `src/` to the [`conda.pth` in site-packages](https://docs.conda.io/projects/conda-build/en/latest/resources/commands/conda-develop.html), but does not install the package. A potentially better solution is to 

`pip install --no-deps -e .`

inside the [conda environment](https://github.com/pinellolab/DNA-Diffusion/blob/b4ba5aac9ad1b3ef6efa4dd2994a5542ac9cf123/environments/conda/environment.yml) that already contains the dependencies. This ensures 

1. (the `pip install` part) that the package is actually installed into the environment, which will allow path-independent access to the local development copy of the library, and
2. (the `--no-deps` part) that inside a conda environment you do not pollute the conda dependency resolution with any PyPI deps

The complication is that there is a bit of manual curation to keep the dependencies in 

* https://github.com/pinellolab/DNA-Diffusion/blob/b4ba5aac9ad1b3ef6efa4dd2994a5542ac9cf123/pyproject.toml
in sync with
* https://github.com/pinellolab/DNA-Diffusion/blob/b4ba5aac9ad1b3ef6efa4dd2994a5542ac9cf123/environments/conda/environment.yml

This is easy to do but not automated. We might be able to automate this if we are able to adopt something with functionality similar to [hatch-conda](https://github.com/OldGrumpyViking/hatch-conda) ([reference in hatch docs](https://hatch.pypa.io/latest/plugins/environment/reference/#known-third-party)). I have not tested this.
