### ISSUE TITLE
REFACTORING: UNET bit diffusion code

### ISSUE THREAD

**Issue by noahweber1** [pinellolab/DNA-Diffusion#141]
@ssean Do you own this ticket and do you want to break this down and get help?

Currently missing:

1. in the src there is dnadiffusion and refactoring, we need to reconcile this
2. cli folder empty
3. logging/w&b set up
4. etc. ?

**Comment by mateibejan1** [comment]
I will work on 1 this week. I think 3 is already done.

**Comment by noahweber1** [comment]
@mateibejan1 when can we expect it wrapped up?

can we help you?
