### ISSUE TITLE
Implement the guided diffusion based on new model

### ISSUE THREAD

**Issue by lucapinello** [pinellolab/DNA-Diffusion#15]
Please use @LucasSilvaFerreira  this notebook as starting point: https://github.com/pinellolab/DNA-Diffusion/blob/dna-diffusion/models/vanilla_diffusion/Code_to_refactor_UNET_ANNOTATED%20v2.ipynb

**Comment by mihirneal** [comment]
@zanussbaum Hey Zack! Would love to work on this. Currently implementing DDPM model from scratch. I think that would be good starting point.

**Comment by zanussbaum** [comment]
hey @mihirneal thanks for the interest! I’ve got a 75% working classifier free guidance working which I’ll upload today/tomorrow. Is there something you’d like to work on after that?

**Comment by mihirneal** [comment]
Cool! Not sure how I can contribute. Do you have something for me to work on?

**Comment by LucasSilvaFerreira** [comment]
@zanussbaum Hi Zach, Let me know when it is ready. I want to test it before providing it to the codebase team.
I will probably be implementing a prototype to measure and check our metrics for the conditional cell type. Thank you

**Comment by mateibejan1** [comment]
hey @zanussbaum are you building on the @LucasSilvaFerreira V2 notebook?
