### ISSUE TITLE
What is a contribution? contribution file linked to read me

### ISSUE THREAD

**Issue by IhabBendidi** [pinellolab/DNA-Diffusion#23]
### Discussed in https://github.com/pinellolab/DNA-Diffusion/discussions/22

<div type='discussions-op-text'>

<sup>Originally posted by **IhabBendidi** October 17, 2022</sup>
An idea is to make a contribution file, to keep account of contributors.
But what is a contribution? 

A code push? that would not count the think tanks that theorized the project, so it is unfair. At the same time, what counts as contibuting discussion, and what isn't? Lines can be blurry in some edge cases.

What are your thoughts?</div>

Contribution list is gonna become huge, and we need to keep proper track of it, so a file would be better, that would be linked to the readme

**Comment by lucapinello** [comment]
We decided to log our initial and weekly contributions here:https://docs.google.com/spreadsheets/d/1_nxDI6DIoWbyUDpIDX-tJIILejrJ0kEYrcXXdWlzPvU/edit#gid=1871728801
