### ISSUE TITLE
support workflow execution from cli

### ISSUE THREAD

**Issue by cameronraysmith** [pinellolab/DNA-Diffusion#272]
- [x] Would currently require downgrade of pandas to `v1.5.3` due to https://github.com/flyteorg/flyte/issues/3928 pinned [here](https://github.com/flyteorg/flytekit/blob/a34ab93532f32a5c28ff65f72a7a7212e986e77c/setup.py#L57). This is being addressed in https://github.com/flyteorg/flytekit/pull/1818 . In the meantime, this can be installed from a fork that may break workflow executions using pandas in IO types.

**Comment by pingsutw** [comment]
@cameronraysmith FYI, flytekit supports Pandas 2 now. https://github.com/flyteorg/flytekit/pull/1818
