### ISSUE TITLE
Use reformers to greatly speed up training time and reduce memory usage

### ISSUE THREAD

**Issue by CamelCaseCam** [pinellolab/DNA-Diffusion#30]
Transformers (like the ones used in your model) have a memory and time complexity of O(n^2). Reformers ([explained here](https://ai.googleblog.com/2020/01/reformer-efficient-transformer.html)) have a memory and time complexity of O(n log n) and, as such, require far less ram and compute to train. 

I am **strongly** suggesting you use reformers since they can replace transformers with almost no change and with a massive benefit. For reference, replacing transformers with reformers on one of my projects took the memory usage down from >10GB to <1GB and was able to train at 45 mins per epoch on an 8-core CPU (I was testing it out before migrating to colab)

**Comment by lucapinello** [comment]
Thanks for the suggestion! Do you have the bandwidth to create a prototype notebook to showcase this based on our current notebook(s)?

**Comment by CamelCaseCam** [comment]
I might be able to give it a try either this weekend or next.

**Comment by lucapinello** [comment]
Sounds great I think the timing is good since @LucasSilvaFerreira and @zanussbaum are going to release a new notebook soon. Keep an eye on the main repo under notebooks/experiments for the latest one.
