### ISSUE TITLE
Implement a sequence quality metric based on k-mer composition

### ISSUE THREAD

**Issue by hssn-20** [pinellolab/DNA-Diffusion#39]

**Comment by lucapinello** [comment]
@hssn-20 if you are still interested in implementing this. See: https://bioinfologics.github.io/post/2018/09/17/k-mer-counting-part-i-introduction/ this is based on Kat: https://github.com/TGAC/KAT
Briefly we can use the hist: Create an histogram of k-mer occurrences from a sequence file. Adds metadata in output for easy plotting.

**Comment by cameronraysmith** [comment]
duplicate of #42
