### ISSUE TITLE
Benchmarking against other tools (GAN paper, Transformer implementation)

### ISSUE THREAD

**Issue by lucapinello** [pinellolab/DNA-Diffusion#40]

**Comment by buttercutter** [comment]
[WGAN-GP model](https://github.com/pinellolab/DNA-Diffusion/blob/7a1ab244f209f0e38e0f060076b580bee9df3359/notebooks/experiments/benchmark/DNA_diffusion_GAN_benchmark.ipynb) needs `enformer`'s [evaluation metric on the generated DNA sequence](https://github.com/pinellolab/DNA-Diffusion/tree/enformer-implementation) (which would require experiment on https://osf.io/uhnb4/'s [K562](K562.PositivePredictions.txt) ABC score)
