### ISSUE TITLE
Develop a standardized PR ticket template

### ISSUE THREAD

**Issue by cmvcordova** [pinellolab/DNA-Diffusion#51]
My interaction over at https://github.com/pinellolab/DNA-Diffusion/pull/50 made me think:

We may or may not have previously talked about setting a template for opening new pull requests. The former interaction has a call for:

1) A link to the ticket it's addressing
2) A small explanation so as to why (based on what though?).

Maybe these two could be good starting points for a default ticket template? _A la,_ copy and paste then fill in with your contribution. Additionally maybe, add if your contribution is going into the codebase/experiments/other folder (or where in the codebase, once it grows), although this is probably filled by 1 already. Anything else you guys consider relevant or good/standard practice?

**Comment by Nwanna-Joseph** [comment]
True @cmvcordova 

Here's a template that works:

**Reference Issues/PRs:**
Sample Answer =  See PR https://github.com/pinellolab/DNA-Diffusion/issues/51

**What does this implement/fix? Explain your changes.**
Sample Answer = Add validators for DummyClassifier and DummyRegressor. Towards https://github.com/scikit-learn/scikit-learn/issues/23462

**Any other comments?**

**Comment by SauravMaheshkar** [comment]
I made a PR with a template in #59.

**Comment by cmvcordova** [comment]
Both are great proposals. We'll implement @SauravMaheshkar 's, as it seems to cover information in both of the proposals and can build from there, as required. Nonetheless, thank you @Nwanna-Joseph for your suggestion!

**Comment by cmvcordova** [comment]
Closing this for now. Additional modifications to the template can be proposed on-the-fly.
