### ISSUE TITLE
Implement W&B logger

### ISSUE THREAD

**Issue by mateibejan1** [pinellolab/DNA-Diffusion#55]

**Comment by Nwanna-Joseph** [comment]
Hi @mateibejan1 . You don't mind if I handle this?

**Comment by Nwanna-Joseph** [comment]
I believe this is to add a logger for weights and biases, right?

**Comment by mateibejan1** [comment]
Sure, you can contribute to this! Join our discord group (OpenBioML) and tag @cmvcordova (Cesare) to discuss progress on this.
